import { Title } from './models';

const seedDate = Date.UTC(2026, 8, 1);
const day = 86400000;

export const seedTitles: Title[] = [
  {
    id: 1,
    slug: 'sintel',
    title: 'Sintel',
    year: 2010,
    genre: 'Fantasy',
    durationMinutes: 15,
    description: 'A lone young woman travels through a harsh, beautiful world in search of the baby dragon she once rescued and raised.',
    streamUrl: 'https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8',
    status: 'published',
    views: 184230,
    createdAt: new Date(seedDate + 1 * day).toISOString(),
    updatedAt: new Date(seedDate + 3 * day).toISOString(),
  },
  {
    id: 2,
    slug: 'big-buck-bunny',
    title: 'Big Buck Bunny',
    year: 2008,
    genre: 'Comedy',
    durationMinutes: 10,
    description: 'A gentle giant of a rabbit has had enough of three small rodents who keep bullying the forest animals, and plans a comical revenge.',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'published',
    views: 152870,
    createdAt: new Date(seedDate + 2 * day).toISOString(),
    updatedAt: new Date(seedDate + 4 * day).toISOString(),
  },
  {
    id: 3,
    slug: 'tears-of-steel',
    title: 'Tears of Steel',
    year: 2012,
    genre: 'Sci-Fi',
    durationMinutes: 12,
    description: 'In a future Amsterdam, a group of scientists and warriors attempt a risky experiment to save the world from destructive robots.',
    streamUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    status: 'published',
    views: 141090,
    createdAt: new Date(seedDate + 3 * day).toISOString(),
    updatedAt: new Date(seedDate + 5 * day).toISOString(),
  },
  {
    id: 4,
    slug: 'elephants-dream',
    title: 'Elephants Dream',
    year: 2006,
    genre: 'Sci-Fi',
    durationMinutes: 11,
    description: 'Two men, Emo and Proog, wander through the endless rooms of a strange mechanical world that only one of them seems to understand.',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'published',
    views: 98450,
    createdAt: new Date(seedDate + 4 * day).toISOString(),
    updatedAt: new Date(seedDate + 6 * day).toISOString(),
  },
  {
    id: 5,
    slug: 'cosmos-laundromat',
    title: 'Cosmos Laundromat',
    year: 2015,
    genre: 'Fantasy',
    durationMinutes: 12,
    description: 'On a desolate island, a disillusioned sheep named Franck meets a mysterious salesman who offers him the chance to live many different lives.',
    streamUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    status: 'published',
    views: 87320,
    createdAt: new Date(seedDate + 5 * day).toISOString(),
    updatedAt: new Date(seedDate + 7 * day).toISOString(),
  },
  {
    id: 6,
    slug: 'spring',
    title: 'Spring',
    year: 2019,
    genre: 'Fantasy',
    durationMinutes: 8,
    description: 'A shepherd girl and her dog face ancient spirits in order to continue the cycle of life.',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'published',
    views: 76610,
    createdAt: new Date(seedDate + 6 * day).toISOString(),
    updatedAt: new Date(seedDate + 8 * day).toISOString(),
  },
  {
    id: 7,
    slug: 'agent-327',
    title: 'Agent 327',
    year: 2017,
    genre: 'Action',
    durationMinutes: 4,
    description: 'Operation Barbershop. Agent 327 goes undercover in a quiet barbershop that hides a far more dangerous secret.',
    streamUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    status: 'published',
    views: 64980,
    createdAt: new Date(seedDate + 7 * day).toISOString(),
    updatedAt: new Date(seedDate + 9 * day).toISOString(),
  },
  {
    id: 8,
    slug: 'sprite-fright',
    title: 'Sprite Fright',
    year: 2021,
    genre: 'Horror Comedy',
    durationMinutes: 10,
    description: 'A group of teenagers on a trip into the forest meet the sprites who live there, and quickly learn they are not as cute as they look.',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'published',
    views: 59240,
    createdAt: new Date(seedDate + 8 * day).toISOString(),
    updatedAt: new Date(seedDate + 10 * day).toISOString(),
  },
  {
    id: 9,
    slug: 'coffee-run',
    title: 'Coffee Run',
    year: 2020,
    genre: 'Drama',
    durationMinutes: 3,
    description: 'Fuelled by caffeine, a young woman races through the bittersweet memories of a past relationship.',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'published',
    views: 41870,
    createdAt: new Date(seedDate + 9 * day).toISOString(),
    updatedAt: new Date(seedDate + 11 * day).toISOString(),
  },
  {
    id: 10,
    slug: 'charge',
    title: 'Charge',
    year: 2022,
    genre: 'Action',
    durationMinutes: 4,
    description: "A high-octane action short set in a dystopian future, made with Blender's real-time EEVEE renderer.",
    streamUrl: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    status: 'published',
    views: 38760,
    createdAt: new Date(seedDate + 10 * day).toISOString(),
    updatedAt: new Date(seedDate + 12 * day).toISOString(),
  },
  {
    id: 11,
    slug: 'hero',
    title: 'Hero',
    year: 2018,
    genre: 'Action',
    durationMinutes: 4,
    description: "A short action piece created to showcase Blender's Grease Pencil tools for 2D animation in a 3D space.",
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'published',
    views: 27450,
    createdAt: new Date(seedDate + 11 * day).toISOString(),
    updatedAt: new Date(seedDate + 13 * day).toISOString(),
  },
  {
    id: 12,
    slug: 'llama-drama',
    title: 'Caminandes: Llama Drama',
    year: 2013,
    genre: 'Comedy',
    durationMinutes: 2,
    description: 'Koro the llama is determined to cross a road in Patagonia, no matter what stands in his way.',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'draft',
    views: 21930,
    createdAt: new Date(seedDate + 12 * day).toISOString(),
    updatedAt: new Date(seedDate + 14 * day).toISOString(),
  },
  {
    id: 13,
    slug: 'gran-dillama',
    title: 'Caminandes: Gran Dillama',
    year: 2013,
    genre: 'Comedy',
    durationMinutes: 2,
    description: 'The grass is always greener on the other side of the fence. Koro sets out to prove it, electric fence or not.',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'draft',
    views: 18640,
    createdAt: new Date(seedDate + 13 * day).toISOString(),
    updatedAt: new Date(seedDate + 15 * day).toISOString(),
  },
  {
    id: 14,
    slug: 'llamigos',
    title: 'Caminandes: Llamigos',
    year: 2016,
    genre: 'Comedy',
    durationMinutes: 3,
    description: 'Winter has come to Patagonia, and Koro meets Oti, a pesky penguin who is after the very same berries.',
    streamUrl: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    status: 'archived',
    views: 12380,
    createdAt: new Date(seedDate + 14 * day).toISOString(),
    updatedAt: new Date(seedDate + 16 * day).toISOString(),
  },
];
